# Generated by Django 4.2.3 on 2023-07-12 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_contact_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='image',
            field=models.ImageField(blank=True, default='img/favour.jpg', null=True, upload_to='image'),
        ),
    ]
